#!/bin/bash

source templates

export PATH=/sbin:/usr/sbin:$PATH
VZPKG=vzpkg
YUM=yum
LIST=${*:-$(${VZPKG} list -O | awk '{print $1}')}
BF=[1m
NF=[0m
GF=[32m
SET_TITLE=']0;'
ST='\\'

log() {
	local d=$(date +%H:%M:%S)
	echo [${GF}${d}${NF}] ${BF}$*${NF}
	echo [$d] $* >> update.log
	echo -ne ${SET_TITLE}[$d] $*${ST}
}

install() {
	local t redo='' i=1
	for t in $*; do
		OS=$(echo $t | sed 's/^\(.*\)-[0-9]-.*$/\1/g')
		ARCH=$(echo $t | sed 's/^.*-.*-\(.*\)-.*$/\1/g')
		V=$(echo $t | sed 's/^.*-\(.*\)-x.*-.*$/\1/g')
		FLAVOR=$(echo $t | sed 's/^.*-.*-.*-\(.*\).*$/\1/g')
		log "[$i/$#] Installing template for $t"
		if ! $YUM install -y $OS-$V-$ARCH; then
			redo="$redo $t"
			log "[$i/$#] Failed to install $t"
		fi
		for f in $FLAVORS; do
			if [ "$t" == "$f" ]; then
				VZPATH=/vz/template/$OS/$V/$ARCH/config/os/;
				mkdir $VZPATH/$FLAVOR;
				ls -1 $VZPATH/default | while read $d; do
					ln -s $VZPATH/default/$d $VZPATH/$FLAVOR/$d;
				done;
				patch --directory $VZPATH/$FLAVOR/ < template/$f
			fi
		done
		let i++
	done
	RE=$redo
}

cache() {
	local t redo='' i=1
	for t in $*; do
		OS=$(echo $t | sed 's/^\(.*\)-[0-9]-.*$/\1/g')
		ARCH=$(echo $t | sed 's/^.*-.*-\(.*\)-.*$/\1/g')
		V=$(echo $t | sed 's/^.*-\(.*\)-x.*-.*$/\1/g')
		FLAVOR=$(echo $t | sed 's/^.*-.*-.*-\(.*\).*$/\1/g')
		log "[$i/$#] Updating cache for $t"
		if ! $VZPKG update cache $OS-$V-$ARCH; then
			redo="$redo $t"
			log "[$i/$#] Failed to update $t"
		fi
		let i++
	done
	RE=$redo
}

if ! test -z "$*"; then
	LIST=$*
fi

log "=== (1) Starting to update templates: $LIST"
install $LIST
cache $LIST
I=2
MAX=5
while test -n "$RE" -a $I -lt $MAX; do
	log "=== ($I/$MAX) The following templates failed, retrying: $RE"
	install $RE
	cache $RE
	let I++
done
if test -z "$RE"; then
	log "=== ($I) All templates were updated succesfully"
	exit 0
else
	log "=== ($I) Some templates were failed to update: $RE"
	exit 1
fi
