#!/bin/bash

source templates

export PATH=/sbin:/usr/sbin:$PATH
VZPKG=vzpkg
YUM=yum
LIST=${*:-$(${VZPKG} list -O | awk '{print $1}')}

log() {
	local d=$(date +%H:%M:%S)
	echo [${d}] $*
	echo [$d] $* >> update.log
	echo -ne [$d] $*
}

isflavor() {
	FLAVOR=$(echo $1 | sed -e 's/^.*-\(minimal\|devel\)$/\1/g')
	[ $FLAVOR == $1 ] && return 1 || return 0;
}

prepare() {
	FLAVOR=$(echo $1 | sed -e 's/^.*-\(minimal\|devel\)$/\1/g')
	NAME=$(echo $t | sed 's/^\(.*\)-\(minimal\|devel\)$/\1/g')
	CONFPATH=`$VZPKG info $NAME config_path | grep template | sed 's/^[ \t]*\(.*\)default$/\1/g'`
	if [ -e $CONFPATH/$FLAVOR ]; then return 0; fi
	mkdir $CONFPATH/$FLAVOR
	cd $CONFPATH/$FLAVOR
	ls -1 ../default/ | while read i; do ln -s ../default/$i $i; done
	cd -
	if ! rpm -q --quiet patch; then
		yum install -y patch
	fi
	cat template/$1 | patch --directory $CONFPATH/$FLAVOR/
}

install() {
	local t i=1
	for t in $*; do
		log "[$i/$#] Installing template for $t"
		if isflavor $t; then
			name=$(echo $t | sed 's/^\(.*\)-\(devel\|minimal\)$/\1/g')
			log "[$i/$#] Full template name is $t, base template is $name"
			if ! $YUM install -y $name"-ez"; then
				log "[$i/$#] Failed to install $name"
				exit 1
			fi
			prepare $t
		else
			if ! $YUM install -y $t"-ez"; then
				log "[$i/$#] Failed to install $t"
				exit 1
			fi
		fi
		let i++
	done
}

cache() {
	local t i=1
	for t in $*; do
		log "[$i/$#] Updating cache for $t"
		if ! $VZPKG update cache $t; then
			log "[$i/$#] Failed to update $t"
			exit 1
		fi
		let i++
	done
}

if ! test -z "$*"; then
	LIST=$*
fi

log "=== (1) Starting to update templates: $LIST"
install $LIST
cache $LIST
